Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,6 +25,16 @@ jobs:
       id-token: 'write'
       contents: 'read'
    steps:
+      - name: Check CONJUR_AUTHN_ID_TEST_GITHUB value
+        run: |
+          if [ "$CONJUR_AUTHN_ID" == "data/apjisppaul03/devops/github-apps/release" ]; then
+            echo "CONJUR_AUTHN_ID is correct."
+          else
+            echo "Error: CONJUR_AUTHN_ID is incorrect or not set properly."
+            exit 1
+          fi
+          env:
+            CONJUR_AUTHN_ID: ${{ secrets.CONJUR_AUTHN_ID }}
       - name: Import Secrets using CyberArk Conjur Secret Fetcher
         uses: cyberark/conjur-action@v2.0.12
         with:
