Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,21 +25,21 @@ jobs:
       id-token: 'write'
       contents: 'read'
    steps:
-      - name: Import Secrets using CyberArk Conjur Secret Fetcher
-        uses: cyberark/conjur-action@v2.0.12
-        with:
-          url: ${{ secrets.CONJUR_URL }}
-          account: conjur
-          authn_id: ${{ secrets.CONJUR_AUTHN_ID_TEST_GITHUB }}
-          secrets: data/vault/github/gh_cr/username;data/vault/github/gh_cr/password|DEV_PASSWORD
-      - name: Validate The Retrieved Secret
-        run: |
-          if [ "$DEV_PASSWORD" == "asdf" ]; then
-            echo "DEV_PASSWORD is correct."
-          else
-            echo "Error: DEV_PASSWORD is incorrect or not set properly."
-            exit 1
-          fi
+   #   - name: Import Secrets using CyberArk Conjur Secret Fetcher
+   #     uses: cyberark/conjur-action@v2.0.12
+   #     with:
+   #       url: ${{ secrets.CONJUR_URL }}
+   #       account: conjur
+   #       authn_id: ${{ secrets.CONJUR_AUTHN_ID_TEST_GITHUB }}
+   #       secrets: data/vault/github/gh_cr/username;data/vault/github/gh_cr/password|DEV_PASSWORD
+   #   - name: Validate The Retrieved Secret
+   #     run: |
+   #       if [ "$DEV_PASSWORD" == "asdf" ]; then
+   #         echo "DEV_PASSWORD is correct."
+   #       else
+   #         echo "Error: DEV_PASSWORD is incorrect or not set properly."
+   #         exit 1
+   #       fi
       - name: Output Run ID
         run: echo ${{ github.run_id }}
       - name: Output Run Number
